server:
  port: 8091

spring:
  application:
    name: StatusChecker

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerWithEureka: true