apiVersion: v1
kind: ConfigMap
metadata:
  name: veiculos
  labels:
    app: veiculos
data:
  application.yml: |-
    server:
      port: 8090

    spring:
      application:
        name: Veiculos
      r2dbc:
        url: r2dbc:h2:mem:///veiculosdb;
        username: test
        password: test
      main:
        allow-bean-definition-overriding: true

    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka
        fetchRegistry: true
        registerWithEureka: true