apiVersion: apps/v1
kind: Deployment
metadata:
  name: veiculos
  labels:
    app: veiculos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: veiculos
  template:
    metadata:
      labels:
        app: veiculos
    spec:
      containers:
      - name: veiculos
        image: veiculos
        ports:
        - containerPort: 8090
        env:
        - name: SPRING_R2DBC_URL
          value: r2dbc:h2:mem:///veiculosdb;
        - name: SPRING_R2DBC_USERNAME
          value: test
        - name: SPRING_R2DBC_PASSWORD
          value: test
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://localhost:8761/eureka
        - name: EUREKA_CLIENT_FETCHREGISTRY
          value: "true"
        - name: EUREKA_CLIENT_REGISTERWITHEUREKA
          value: "true"