CREATE TABLE IF NOT EXISTS VEICULO_MODEL (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    marca VARCHAR(255) NOT NULL,
    modelo VARCHAR(255) NOT NULL,
    ano VARCHAR(255) NOT NULL,
    placa VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)

    
);