server:
  port: 8093

spring:
  application:
    name: CatFact
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerWithEureka: true

catfact:
  url: https://catfact.ninja/fact